Repository corona-warn-app/cwa-verification-iam, pull requests merged in 2020-06, with the labels that each got.

#41 fixing a typo
  src/themes/cwa/login/login-update-password.ftl
Labels: in review

#31 Content-Security-Policy header added to all html pages
  src/themes/cwa/login/login-config-totp.ftl
  src/themes/cwa/login/login-otp.ftl
  src/themes/cwa/login/login-update-password.ftl
  src/themes/cwa/login/login.ftl
Labels: bug

#39 Fix: [BSI][20200609] Autocomplete Enabled on Password Field
  src/themes/cwa/login/login.ftl
Labels: bug

#42 Password Change Feature
  Dockerfile
  src/standalone/configuration/standalone-ha.xml
  src/themes/cwa/account/messages/messages_de.properties
  src/themes/cwa/account/password.ftl
  src/themes/cwa/account/resources/img/c-19_logo.png
  src/themes/cwa/account/resources/img/data_protect.png
  src/themes/cwa/account/resources/img/life_is_for_sharing.png
  src/themes/cwa/account/resources/img/telekom_web_logo.png
  src/themes/cwa/account/resources/img/user.png
  src/themes/cwa/account/resources/logout.js
  src/themes/cwa/account/resources/password.css
  src/themes/cwa/account/resources/telegrotesknext-bold.woff
  src/themes/cwa/account/resources/telegrotesknext-regular.woff
  src/themes/cwa/account/resources/telegrotesknext-thin.woff
  src/themes/cwa/account/template.ftl
  src/themes/cwa/account/theme.properties
Labels: enhancement

#37 feat: added recommended ciphers. included TLSv1.3
  Dockerfile
  README.md
  src/standalone/configuration/keystores/test-only-https-keystore.jks
  src/standalone/configuration/standalone-ha.xml
Labels: implemented, security
